# Generated by Django 4.2.16 on 2024-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(upload_to='stories/'),
        ),
    ]
