# Generated by Django 4.2.16 on 2024-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_is_published_alter_story_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='stories_pdfs/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
